name: Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL Service
        run: sudo systemctl start postgresql

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Setup Database
        run: PGPASSWORD=${{ secrets.PGPASSWORD }} psql -h localhost -p 5433 -U ${{ secrets.PGUSER }} -d ${{ secrets.PGDATABASE }} -f ./db/setup-dbs.sql
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGHOST: localhost
          PGPORT: 5433

      - name: Seed Database
        run: npm run seed-dev
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGHOST: localhost
          PGPORT: 5433

      - name: Run tests
        run: npm test
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGHOST: localhost
          PGPORT: 5433