name: Test & Delploy

on:
  push: 
    branch:
     - main

jobs:
  test:
    runs-on: ubtuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
      
      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: ${{ secrets.PGDATABASE }}
          postgresql user: ${{ secrets.PGUSER }}
          postgresql password: ${{ secrets.PGPASSWORD }}
      
      - name: Install dependencies
        run: npm ci
       
      - name: Setup Database
        run: npm run setup-dbs
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
      
      - name: Seed Database
        run: npm run seed-dev
        end: 
          PGDATABASE: ${{ secrets.PGDATABASE }}
      
      - name: Run Tests
        run: PGDATABASE=${{ secrets.PGDATABASE }} PGUSER=${{ secrets.PGUSER }} PGPASSWORD=${{ secrets.PGPASSWORD }} npm t